title: "Craps Simulation"
author: "Jenn Derkits"

project:
  output-dir: _output
  render:
    - README.md
    - pseudocode.qmd
    - craps-code.qmd
    - simulation.qmd


output: html_document


